# Generated by Django 5.1.7 on 2025-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_produit', '0005_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nb_products',
            field=models.IntegerField(default=0),
        ),
    ]
