# Generated by Django 5.1.7 on 2025-05-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_produit', '0006_categorie_nb_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='nb_products',
        ),
    ]
